"""Tests for the exclude policy / exempt_dirs design.

This file covers the consolidation work that replaces:
  - ``docgen.staleness._EXCLUDED_DIRS``  (private hardcoded list)
  - ``docgen.catalog_writer._SKIP_DIR_NAMES``  (private hardcoded list)

with a single canonical default in ``config.py`` (``DEFAULT_EXCLUDE_POLICY``),
optionally overridable at the top level of ``ariadne.yaml`` via
``exclude_policy:``, plus a per-source ``exempt_dirs:`` field that
*subtracts* from the effective set.

The effective excluded-dir set per source is:

    (config.exclude_policy ∪ source.exclude_dirs) − source.exempt_dirs

Behavior contracts asserted here:

  * Built-in default is comprehensive (includes the obvious never-walk
    names: ``.git``, ``node_modules``, ``__pycache__``, ``.venv``,
    ``dist``, ``target``, ...).
  * ``exclude_policy:`` in ``ariadne.yaml`` REPLACES the default — empty
    tuple means a full walk.
  * Per-source ``exclude_dirs:`` UNIONS with the policy.
  * Per-source ``exempt_dirs:`` SUBTRACTS from the union (rare opt-out
    for projects that legitimately have a ``dist/`` worth indexing).
  * Duplicate names between ``exclude_policy`` and per-source
    ``exclude_dirs`` are silently deduplicated (idempotent).
  * Overlap between per-source ``exclude_dirs`` and ``exempt_dirs``
    is a contradiction and MUST raise at config load time so the user
    fixes the config rather than getting silent surprising behavior.
  * ``find_python_files`` / ``find_catalog_files`` / ``iter_catalog_files``
    all consume the same resolved set — no two-list drift.
"""
from __future__ import annotations

from pathlib import Path

import pytest


class TestDefaultFileExcludePatterns:
    """Companion to DEFAULT_EXCLUDE_POLICY (dirs): the canonical default for
    vendored *files* that are never project source — pip/poetry bootstrap
    installers like ``get-pip.py``. Same no-drift contract as the dir policy:
    a single source in config.py, consumed by every discovery path.
    """

    def test_default_includes_vendored_installers(self) -> None:
        from config import DEFAULT_EXCLUDE_FILE_PATTERNS
        assert '**/get-pip.py' in DEFAULT_EXCLUDE_FILE_PATTERNS

    def test_find_catalog_files_excludes_get_pip_by_default(
        self, tmp_path: Path,
    ) -> None:
        from docgen.staleness import find_catalog_files
        (tmp_path / 'get-pip.py').write_text('# vendored pip installer\n')
        (tmp_path / 'real.py').write_text('def foo():\n    return 1\n')
        names = {p.name for p in find_catalog_files(tmp_path)}
        assert 'real.py' in names
        assert 'get-pip.py' not in names

    def test_find_python_files_excludes_get_pip_by_default(
        self, tmp_path: Path,
    ) -> None:
        from docgen.staleness import find_python_files
        (tmp_path / 'get-pip.py').write_text('# vendored pip installer\n')
        (tmp_path / 'real.py').write_text('def foo():\n    return 1\n')
        names = {p.name for p in find_python_files(tmp_path)}
        assert 'real.py' in names
        assert 'get-pip.py' not in names


# ---------------------------------------------------------------------------
# Default policy: shape and content
# ---------------------------------------------------------------------------


def test_default_exclude_policy_contains_expected_names():
    """The built-in default must cover the obvious never-walk dirs.

    These are the names the user explicitly named when proposing the
    feature. Any future addition is welcome but these MUST be present.
    """
    from config import DEFAULT_EXCLUDE_POLICY

    must_contain = {
        '.git', '.venv', 'venv',
        'node_modules', '__pycache__',
        'dist', 'build',
        'target',  # JVM/Scala/Rust
        '.idea', '.vscode',
        '.mypy_cache', '.pytest_cache', '.ruff_cache',
    }
    missing = must_contain - set(DEFAULT_EXCLUDE_POLICY)
    assert not missing, (
        f'DEFAULT_EXCLUDE_POLICY is missing expected names: {sorted(missing)}'
    )


def test_default_policy_covers_all_supported_languages():
    """For every language/tool Ariadne indexes, the policy excludes the
    canonical autogenerated and cache directories that ecosystem produces.

    Driven by the CATALOG_EXTS list (each extension is paired below with
    the build/cache dirs that ecosystem creates). When a new language
    lands in CATALOG_EXTS, add its build artifacts to the table below
    AND to DEFAULT_EXCLUDE_POLICY. This test fails the moment the policy
    drifts from the supported-language matrix.
    """
    from config import DEFAULT_EXCLUDE_POLICY

    expected_by_ecosystem: dict[str, set[str]] = {
        # Python (.py) — interpreter/test/typecheck caches + venvs
        'python': {
            '__pycache__', '.venv', 'venv', 'env',
            '.pytest_cache', '.mypy_cache', '.ruff_cache',
            '.tox', '.nox', '.hypothesis',
            'site-packages', '.eggs',
        },
        # JavaScript / TypeScript (.js / .jsx / .ts / .tsx / .mjs)
        # Package managers + framework dev caches + vendored ESM bundles.
        'javascript_typescript': {
            'node_modules', 'web_modules',
            'bower_components', 'jspm_packages',
            '.next', '.nuxt', '.svelte-kit',
            '.cache', '.parcel-cache', '.turbo',
            '.vite', '.angular',
            '.docusaurus', '.umi', 'storybook-static',
            '__generated__',
        },
        # JS / TS deploy / hosting platform caches
        'js_deploy_caches': {
            '.vercel', '.netlify',
        },
        # Scala / Java (.scala / .sbt / .java) — JVM build tooling
        'scala_java': {
            'target', '.gradle', '.bsp', '.metals', '.bloop',
            '.scala-build',
        },
        # Test / coverage output (cross-language)
        'test_coverage': {
            'coverage', 'htmlcov', '.coverage',
        },
        # Infra-as-code build caches that show up in monorepos and that
        # we never want indexed (binary plan files, downloaded providers).
        'iac_cloud': {
            '.terraform', '.pulumi', '.serverless', '.aws-sam',
            '.firebase', '.cdk.out',
        },
        # Generic build output (matches every compiled language)
        'generic_build': {
            'build', 'dist', 'out',
        },
        # IDE / editor metadata
        'ide': {
            '.idea', '.vscode', '.vs', '.fleet',
        },
        # Generated docs / static sites
        'generated_docs': {
            '_site', 'generated-docs',
        },
        # VCS metadata (HOCON / config / everything)
        'vcs': {
            '.git', '.hg', '.svn',
        },
        # Vendored deps (Go modules vendor dir, PHP composer vendor, etc.)
        'vendor': {
            'vendor',
        },
    }

    policy = set(DEFAULT_EXCLUDE_POLICY)
    failures: list[str] = []
    for ecosystem, names in expected_by_ecosystem.items():
        missing = names - policy
        if missing:
            failures.append(
                f"{ecosystem}: missing {sorted(missing)}"
            )

    assert not failures, (
        'DEFAULT_EXCLUDE_POLICY is missing autogenerated-content '
        'entries for one or more supported ecosystems:\n  '
        + '\n  '.join(failures)
    )


def test_default_exclude_policy_is_a_tuple_of_strings():
    """The constant is a tuple (immutable, hashable) of plain strings."""
    from config import DEFAULT_EXCLUDE_POLICY

    assert isinstance(DEFAULT_EXCLUDE_POLICY, tuple)
    assert all(isinstance(d, str) for d in DEFAULT_EXCLUDE_POLICY)


# ---------------------------------------------------------------------------
# Top-level ``exclude_policy:`` field on Config
# ---------------------------------------------------------------------------


def test_config_exclude_policy_returns_default_when_unset(tmp_path):
    """Config without an ``exclude_policy`` key returns the default."""
    from config import Config, DEFAULT_EXCLUDE_POLICY

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text('sources: {}\n', encoding='utf-8')
    cfg = Config(config_path=yaml_path)
    assert cfg.exclude_policy == DEFAULT_EXCLUDE_POLICY


def test_config_exclude_policy_user_override_replaces_default(tmp_path):
    """A user-set ``exclude_policy:`` REPLACES the default (no merge)."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'exclude_policy:\n'
        '  - .git\n'
        '  - node_modules\n'
        'sources: {}\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    assert cfg.exclude_policy == ('.git', 'node_modules')


def test_config_exclude_policy_empty_list_means_full_walk(tmp_path):
    """``exclude_policy: []`` is honored — a user that *wants* a full
    walk can opt out of the default. Unusual, but explicit."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'exclude_policy: []\n'
        'sources: {}\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    assert cfg.exclude_policy == ()


# ---------------------------------------------------------------------------
# Per-source ``exempt_dirs:`` field
# ---------------------------------------------------------------------------


def test_source_config_has_exempt_dirs_default_empty():
    from config import SourceConfig

    sc = SourceConfig(path='/tmp/x')
    assert sc.exempt_dirs == ()


def test_source_config_accepts_exempt_dirs_tuple():
    from config import SourceConfig

    sc = SourceConfig(path='/tmp/x', exempt_dirs=('dist', 'build'))
    assert sc.exempt_dirs == ('dist', 'build')


def test_config_reads_exempt_dirs_from_yaml(tmp_path):
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'sources:\n'
        '  legacy-frontend:\n'
        '    path: /tmp/legacy-frontend\n'
        '    exempt_dirs:\n'
        '      - dist\n'
        '      - target\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    sc = cfg.get_source_config('legacy-frontend')
    assert sc is not None
    assert sc.exempt_dirs == ('dist', 'target')


# ---------------------------------------------------------------------------
# Resolved exclusion set: policy ∪ exclude_dirs − exempt_dirs
# ---------------------------------------------------------------------------


def test_resolve_excluded_dirs_unions_policy_and_source_exclude_dirs(tmp_path):
    """Per-source ``exclude_dirs`` adds to the global policy."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'exclude_policy:\n'
        '  - .git\n'
        '  - node_modules\n'
        'sources:\n'
        '  myapp:\n'
        '    path: /tmp/myapp\n'
        '    exclude_dirs:\n'
        '      - charts\n'
        '      - image_archives\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    resolved = set(cfg.resolve_excluded_dirs('myapp'))
    assert resolved == {'.git', 'node_modules', 'charts', 'image_archives'}


def test_resolve_excluded_dirs_subtracts_exempt_dirs(tmp_path):
    """Per-source ``exempt_dirs`` removes from the otherwise-excluded set."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'exclude_policy:\n'
        '  - .git\n'
        '  - node_modules\n'
        '  - dist\n'
        'sources:\n'
        '  legacy-frontend:\n'
        '    path: /tmp/legacy-frontend\n'
        '    exempt_dirs:\n'
        '      - dist\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    resolved = set(cfg.resolve_excluded_dirs('legacy-frontend'))
    assert resolved == {'.git', 'node_modules'}
    assert 'dist' not in resolved


def test_resolve_excluded_dirs_idempotent_for_duplicate_name(tmp_path):
    """A name appearing in both ``exclude_policy`` and per-source
    ``exclude_dirs`` is silently deduplicated — no error, no warning,
    and no double-counting in the resolved set."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'exclude_policy:\n'
        '  - .git\n'
        '  - node_modules\n'
        'sources:\n'
        '  myapp:\n'
        '    path: /tmp/myapp\n'
        '    exclude_dirs:\n'
        '      - node_modules\n'
        '      - charts\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    resolved = list(cfg.resolve_excluded_dirs('myapp'))
    # Sorted result should not duplicate node_modules
    assert resolved.count('node_modules') == 1
    assert set(resolved) == {'.git', 'node_modules', 'charts'}


def test_resolve_excluded_dirs_returns_default_policy_when_no_source_overrides(
    tmp_path,
):
    """A vanilla source with no ``exclude_dirs`` / ``exempt_dirs``
    inherits exactly the global policy."""
    from config import Config, DEFAULT_EXCLUDE_POLICY

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'sources:\n'
        '  myapp:\n'
        '    path: /tmp/myapp\n',
        encoding='utf-8',
    )
    cfg = Config(config_path=yaml_path)
    resolved = set(cfg.resolve_excluded_dirs('myapp'))
    assert resolved == set(DEFAULT_EXCLUDE_POLICY)


# ---------------------------------------------------------------------------
# Validation: contradiction between exclude_dirs and exempt_dirs
# ---------------------------------------------------------------------------


def test_config_load_raises_when_exclude_dirs_and_exempt_dirs_overlap(tmp_path):
    """A source listing the same dir in both ``exclude_dirs`` and
    ``exempt_dirs`` is contradictory ("skip" + "do not skip"). Surface
    it loudly at load — the user must fix the config before running."""
    from config import Config, ConfigError

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'sources:\n'
        '  myapp:\n'
        '    path: /tmp/myapp\n'
        '    exclude_dirs:\n'
        '      - dist\n'
        '      - generated\n'
        '    exempt_dirs:\n'
        '      - dist\n',
        encoding='utf-8',
    )
    with pytest.raises(ConfigError) as excinfo:
        Config(config_path=yaml_path)

    msg = str(excinfo.value)
    # Error must name both the source and the offending dir so the user
    # can find and fix it without spelunking.
    assert 'myapp' in msg
    assert 'dist' in msg


def test_config_load_does_not_raise_on_no_overlap(tmp_path):
    """Non-overlapping exclude_dirs / exempt_dirs is fine."""
    from config import Config

    yaml_path = tmp_path / 'ariadne.yaml'
    yaml_path.write_text(
        'sources:\n'
        '  myapp:\n'
        '    path: /tmp/myapp\n'
        '    exclude_dirs:\n'
        '      - generated\n'
        '    exempt_dirs:\n'
        '      - dist\n',
        encoding='utf-8',
    )
    # Should construct without error.
    cfg = Config(config_path=yaml_path)
    sc = cfg.get_source_config('myapp')
    assert sc is not None
    assert sc.exclude_dirs == ('generated',)
    assert sc.exempt_dirs == ('dist',)


# ---------------------------------------------------------------------------
# Discovery layer: both walk paths use the same default policy
# ---------------------------------------------------------------------------


def test_find_catalog_files_default_excludes_policy_dirs(tmp_path):
    """When ``exclude_dir_names`` is not supplied, ``find_catalog_files``
    falls back to the canonical default policy — every name in the
    policy is pruned at every depth.

    ``target`` and ``.idea`` are deliberately NEW additions (absent
    from the legacy ``_EXCLUDED_DIRS``). If implementation still relies
    on the old hardcoded list, these will leak and the test will fail.
    """
    from config import DEFAULT_EXCLUDE_POLICY
    from docgen.staleness import find_catalog_files

    (tmp_path / 'src').mkdir()
    (tmp_path / 'src' / 'main.py').write_text('x = 1', encoding='utf-8')
    excluded_names = ('node_modules', '__pycache__', '.venv', 'target', '.idea')
    for excluded in excluded_names:
        d = tmp_path / excluded
        d.mkdir()
        (d / 'leaked.py').write_text('y = 2', encoding='utf-8')

    # Sanity: every name is in the default policy, otherwise this test
    # would silently pass for the wrong reason.
    for name in excluded_names:
        assert name in DEFAULT_EXCLUDE_POLICY, (
            f'{name} expected in DEFAULT_EXCLUDE_POLICY'
        )

    files = find_catalog_files(tmp_path)
    rels = sorted(str(f.relative_to(tmp_path)) for f in files)

    assert 'src/main.py' in rels
    for excluded in excluded_names:
        leaked = [r for r in rels if r.startswith(f'{excluded}/')]
        assert not leaked, (
            f'{excluded} subtree leaked: {leaked} '
            '(default policy not honored)'
        )


def test_find_python_files_default_excludes_policy_dirs(tmp_path):
    """``find_python_files`` honors the same default policy.

    ``target`` is in the new policy but NOT in the legacy
    ``_EXCLUDED_DIRS``, so this test bites if the function still
    consults the old constant.
    """
    from docgen.staleness import find_python_files

    (tmp_path / 'src').mkdir()
    (tmp_path / 'src' / 'main.py').write_text('x = 1', encoding='utf-8')
    excluded_names = ('node_modules', '__pycache__', '.venv', 'target')
    for excluded in excluded_names:
        d = tmp_path / excluded
        d.mkdir()
        (d / 'leaked.py').write_text('y = 2', encoding='utf-8')

    files = find_python_files(tmp_path)
    rels = sorted(str(f.relative_to(tmp_path)) for f in files)

    assert 'src/main.py' in rels
    for excluded in excluded_names:
        assert not any(r.startswith(f'{excluded}/') for r in rels), (
            f'{excluded} subtree leaked from find_python_files'
        )


def test_iter_catalog_files_default_excludes_policy_dirs(tmp_path):
    """``iter_catalog_files`` (catalog-sync's discovery) honors the
    same default policy — no more two-list drift."""
    from docgen.catalog_writer import iter_catalog_files

    (tmp_path / 'src').mkdir()
    (tmp_path / 'src' / 'main.py').write_text('x = 1', encoding='utf-8')
    for excluded in ('node_modules', '__pycache__', '.venv', 'target'):
        d = tmp_path / excluded
        d.mkdir()
        (d / 'leaked.py').write_text('y = 2', encoding='utf-8')

    files = iter_catalog_files(tmp_path)
    rels = sorted(str(f.relative_to(tmp_path)) for f in files)

    assert 'src/main.py' in rels
    for excluded in ('node_modules', '__pycache__', '.venv', 'target'):
        assert not any(r.startswith(f'{excluded}/') for r in rels), (
            f'{excluded} leaked from iter_catalog_files'
        )


def test_two_walk_paths_use_same_default_policy(tmp_path):
    """Regression guard: ``find_catalog_files`` and ``iter_catalog_files``
    must produce the same set of skipped directories for the same tree.

    Previously, ``staleness._EXCLUDED_DIRS`` and
    ``catalog_writer._SKIP_DIR_NAMES`` had drifted (e.g., ``.hg`` was in
    one but not the other; ``generated-docs`` only in the other). This
    test fails until both code paths consult the single canonical
    policy."""
    from docgen.catalog_writer import iter_catalog_files
    from docgen.staleness import find_catalog_files

    (tmp_path / 'src').mkdir()
    (tmp_path / 'src' / 'main.py').write_text('x = 1', encoding='utf-8')

    # Names historically in only ONE of the two private lists. After the
    # consolidation, both walks must skip both.
    for name in ('.hg', 'generated-docs', '.svn', '_site'):
        d = tmp_path / name
        d.mkdir()
        (d / 'leak.py').write_text('z = 3', encoding='utf-8')

    a = sorted(str(f.relative_to(tmp_path)) for f in find_catalog_files(tmp_path))
    b = sorted(str(f.relative_to(tmp_path)) for f in iter_catalog_files(tmp_path))

    assert a == b, (
        'find_catalog_files and iter_catalog_files diverged: '
        f'{set(a) ^ set(b)}'
    )
