"""Round-trip-safe ariadne.yaml mutation (Phase 2j.c).

When ``ariadne discover --review`` accepts a user's reject decision,
the suggested exclude pattern needs to land in ``ariadne.yaml`` under
``sources.<name>.exclude``. PyYAML can read+modify+write but loses
comments and reflows the file. Users would hate that.

ruamel.yaml's RoundTripLoader is purpose-built for this — it
preserves comments, line ordering, anchors, and formatting on
round-trip. Hence the new dependency.

This module exposes a single function (:func:`append_source_excludes`)
that adds patterns idempotently. Existing patterns are left in place
(no duplicates); new patterns are appended to the end of the source's
``exclude`` list.
"""
from __future__ import annotations

from pathlib import Path

from ruamel.yaml import YAML


def append_source_excludes(
    yaml_path: Path,
    source_name: str,
    new_patterns: list[str],
) -> int:
    """Append exclude patterns to a source's ``exclude:`` list.

    Returns the count of patterns ACTUALLY added (skipping any that
    were already present). On a no-op (empty input or all duplicates),
    the file is not rewritten.

    Raises:
        FileNotFoundError: if ``yaml_path`` does not exist.
        KeyError: if ``source_name`` is not in ``sources:``.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f'No yaml at {yaml_path}')
    if not new_patterns:
        return 0

    yaml = YAML()
    yaml.preserve_quotes = True
    # Match common ariadne.yaml indent style (2-space mapping, 2-space
    # sequence offset). ruamel preserves the original on round-trip
    # anyway; this is just defaults for new keys we create.
    yaml.indent(mapping=2, sequence=4, offset=2)

    # SAFETY: `yaml` here is a ruamel.yaml.YAML instance (round-trip
    # loader, typ='rt'), NOT the PyYAML module — so `yaml.load` below
    # does NOT honor `!!python/*` tags and cannot deserialize arbitrary
    # objects (verified: every classic PyYAML RCE payload loads as inert
    # data through this exact path). Static scanners that string-match
    # `yaml.load(` flag it as unsafe PyYAML; that is a false positive.
    # Defense in depth: the runtime config reader (config.py) uses
    # yaml.safe_load, which fails closed (ConstructorError) on such tags.
    with yaml_path.open('r', encoding='utf-8') as f:
        data = yaml.load(f)

    sources = data.get('sources') if data is not None else None
    if not sources or source_name not in sources:
        raise KeyError(
            f'Source {source_name!r} not found in {yaml_path}',
        )

    src = sources[source_name]
    existing = src.get('exclude') if src else None
    if existing is None:
        existing = []

    # Build the updated exclude list; track count of additions.
    added_count = 0
    updated = list(existing)
    for pattern in new_patterns:
        if pattern not in updated:
            updated.append(pattern)
            added_count += 1

    if added_count == 0:
        return 0

    src['exclude'] = updated

    with yaml_path.open('w', encoding='utf-8') as f:
        yaml.dump(data, f)

    return added_count


_AUTO_MANAGED_COMMENT = (
    'Ariadne-managed below this line — '
    'regenerated by `ariadne discover`'
)


def write_source_scip_config(
    yaml_path: Path,
    source_name: str,
    *,
    catalog_scip_languages: set[str],
    artifact_path: Path | str,
    max_staleness_days: int = 7,
) -> bool:
    """Idempotently author the auto-managed ``index_kinds`` +
    ``scip:`` block for a source.

    Per the UX principle that ``ariadne.yaml`` should carry only
    user-authored fields (``path`` / ``depends_on`` / ``exclude`` /
    ``exclude_dirs``), this helper lets ``ariadne discover`` write
    every SCIP-related field that the rest of Ariadne needs.
    Subsequent ``discover`` runs are no-ops when the block already
    matches detection — the YAML stays stable across re-runs.

    ``catalog_scip_languages`` is the set of languages whose catalog
    extraction should route through SCIP (today: subset of
    ``{'scala', 'java', 'javascript'}`` — the languages
    ``catalog_extractor.extract_elements`` routes through
    ``scip_extractor`` when declared). Python is detected and indexed
    for cross-source data, but its catalog extraction stays on
    ast-grep because ast-grep's qualified_names already match what
    scip-python emits — no routing layer needed.

    Returns True if the file was rewritten, False if the content
    already matched the requested state.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f'No yaml at {yaml_path}')

    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.indent(mapping=2, sequence=4, offset=2)

    # SAFETY: ruamel round-trip loader, not PyYAML — safe by default.
    # See the note in append_source_excludes above re: why `yaml.load`
    # here cannot execute arbitrary code (scanner false positive).
    with yaml_path.open('r', encoding='utf-8') as f:
        data = yaml.load(f)

    sources = data.get('sources') if data is not None else None
    if not sources or source_name not in sources:
        raise KeyError(
            f'Source {source_name!r} not found in {yaml_path}',
        )

    src = sources[source_name]
    if src is None:
        # ``sources.X:`` with nothing under it — shorthand for
        # ``sources.X: {path: ...}`` from a previous version. Coerce
        # to a real mapping so we have somewhere to write.
        src = {}
        sources[source_name] = src

    artifact_str = str(artifact_path)

    # Build expected state — sorted keys so re-runs are deterministic.
    expected_index_kinds = {
        lang: 'scip' for lang in sorted(catalog_scip_languages)
    }
    expected_scip = {
        'artifact_path': artifact_str,
        'max_staleness_days': max_staleness_days,
    }

    current_index_kinds = src.get('index_kinds') or {}
    current_scip = src.get('scip') or {}

    # Treat both as ordinary dicts for comparison (ruamel uses
    # CommentedMap, which compares equal to plain dict when keys
    # + values match).
    if (
        dict(current_index_kinds) == expected_index_kinds
        and dict(current_scip) == expected_scip
    ):
        return False

    src['index_kinds'] = expected_index_kinds
    src['scip'] = expected_scip

    with yaml_path.open('w', encoding='utf-8') as f:
        yaml.dump(data, f)

    return True


__all__ = ['append_source_excludes', 'write_source_scip_config']
